2.3. Linear Algebra

By now, we can load datasets into tensors and manipulate these tensors with basic mathematical operations. To start building sophisticated models, we will also need a few tools from linear algebra. This section offers a gentle introduction to the most essential concepts, starting from scalar arithmetic and ramping up to matrix multiplication.

In [254]:
import torch

In [255]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [256]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [257]:
x[2]

tensor(2)

In [258]:
len(x)

3

In [259]:
x.shape

torch.Size([3])

In [260]:
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [261]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [262]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [263]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [264]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()  # Assign a copy of A to B by allocating new memory
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [265]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

2.3.13. Exercises

1. Prove that the transpose of the transpose of a matrix is the matrix itself: (**A**<sup>T</sup>)<sup>T</sup> = **A**

In [266]:
A = torch.arange(9, dtype=torch.float32).reshape(3, 3)
A

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [267]:
A.T

tensor([[0., 3., 6.],
        [1., 4., 7.],
        [2., 5., 8.]])

In [268]:
A.T.T == A

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

2. Given two matrices **A** and **B**, show that sum and transposition commute: **A**<sup>T</sup> + **B**<sup>T</sup> = (**A** + **B**)<sup>T</sup>

In [269]:
B = A*2
B

tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.],
        [12., 14., 16.]])

In [270]:
A + B

tensor([[ 0.,  3.,  6.],
        [ 9., 12., 15.],
        [18., 21., 24.]])

In [271]:
A.T + B.T

tensor([[ 0.,  9., 18.],
        [ 3., 12., 21.],
        [ 6., 15., 24.]])

In [272]:
(A + B).T

tensor([[ 0.,  9., 18.],
        [ 3., 12., 21.],
        [ 6., 15., 24.]])

In [273]:
(A + B).T == A.T + B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

3. Given any square matrix **A**, is **A** + **A**<sup>T</sup> always symmetric? Can you prove the result by using only the results of the previous two exercises?

In [274]:
A, A.T

(tensor([[0., 1., 2.],
         [3., 4., 5.],
         [6., 7., 8.]]),
 tensor([[0., 3., 6.],
         [1., 4., 7.],
         [2., 5., 8.]]))

In [275]:
A + A.T

tensor([[ 0.,  4.,  8.],
        [ 4.,  8., 12.],
        [ 8., 12., 16.]])

In [276]:
(A + A.T).T == (A + A.T)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [277]:
(A + A.T).T == (A.T + A.T.T)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

4. We defined the tensor X of shape (2, 3, 4) in this section. What is the output of len(X)? Write your answer without implementing any code, then check your answer using code.

In [278]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [279]:
len(X)

2

5. For a tensor X of arbitrary shape, does len(X) always correspond to the length of a certain axis of X? What is that axis?

A: The first dimension, or X axis.

6. Run A / A.sum(axis=1) and see what happens. Can you analyze the results?

In [280]:
A.sum(axis=1), A / A.sum(axis=1)

(tensor([ 3., 12., 21.]),
 tensor([[0.0000, 0.0833, 0.0952],
         [1.0000, 0.3333, 0.2381],
         [2.0000, 0.5833, 0.3810]]))

7. When traveling between two points in downtown Manhattan, what is the distance that you need to cover in terms of the coordinates, i.e., in terms of avenues and streets? Can you travel diagonally?

A: 
The sum of difference of X and Y assuming one can't move diagonally between blocks.
- In downtown Manhattan, streets are rectilinearly distributed, and one has to travel from point $(x_1, y_1) to (x_2, y_2)$ along a trajectory composed of only horizontal and vertical lines.
  - In such a case, the shortest distance to travel is $|x_1 - x_2|+|y_1 - y_2|$.
- For a given space with dimension n1, the [Manhattan distance](https://en.wikipedia.org/wiki/Taxicab_geometry) between two points p and q is defined as $d_T$(p, q) := $\displaystyle\sum_{i=1}^n |p_i - q_i|$.
  - This is applicable in signal processing, Machine Learning models, etc.

In [281]:
manhattan = torch.ones((10, 10))
manhattan #assuming all blocks are evenly spaced and starting in the top left corner

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

8. Consider a tensor of shape (2, 3, 4). What are the shapes of the summation outputs along axes 0, 1, and 2?

In [282]:
X = torch.arange(24).reshape(2, 3, 4)
X, X.sum(axis=0), X.sum(axis=1), X.sum(axis=2)

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]),
 tensor([[12, 15, 18, 21],
         [48, 51, 54, 57]]),
 tensor([[ 6, 22, 38],
         [54, 70, 86]]))

9. Feed a tensor with three or more axes to the linalg.norm function and observe its output. What does this function compute for tensors of arbitrary shape?

In [283]:
X = torch.arange(24, dtype=torch.float64).reshape(2, 3, 4)
X, torch.linalg.norm(X)

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.]],
 
         [[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.]]], dtype=torch.float64),
 tensor(65.7571, dtype=torch.float64))

A: torch.linalg.norm() computes the Frobenius norm for matrices (2D tensors) and the L2 norm for tensors with more than two dimensions. Thus, the previous result represents the magnitude of the vector in a high-dimensional space formed by flattening the tensor X. Applying this function “forcefully”:

In [284]:
torch.sqrt(torch.sum(X ** 2))

tensor(65.7571, dtype=torch.float64)

10. Consider three large matrices, say $\mathbf{A}\in \mathbb{R}^{2^{10}\times2^{16}}$, $\mathbf{B}\in \mathbb{R}^{2^{16}\times2^{5}}$ and $\mathbf{C}\in \mathbb{R}^{2^{5}\times2^{14}}$, initialized with Gaussian random variables. You want to compute the product $\mathbf{ABC}$. Is there any difference in memory footprint and speed, depending on whether you compute $\mathbf{(AB)C}$ or $\mathbf{A(BC)}$. Why?

$ (\mathbf{A} \mathbf{B}) \mathbf{C} $ will result in time being $ \mathcal{O}(2^{10} \times 2^{16} \times 2^5 + 2^{10} \times 2^{5} \times 2^{16} ) $

$ \mathbf{A} (\mathbf{B} \mathbf{C}) $ will result in time being $ \mathcal{O}(2^{10} \times 2^{16} \times 2^{16} + 2^{16} \times 2^{5} \times 2^{16} ) $

The latter is much much more expensive because of the algorithms being designed to have complexity of $ \mathcal{O}(n \times m \times k) $ where the matrices $ A $ and $ B $ are of size $ \mathbb{R}^{n \times m} $ and $ \mathbb{R}^{m \times k} $ respectively

In [285]:
import psutil
import time

def memory(X, Y):
    start = time.time()
    torch.mm(X, Y)
    memory = psutil.virtual_memory()
    print(f"Total system memory: {memory.total / (1024 ** 3):.2f} GB")
    print(f"Memory used: {memory.used / (1024 ** 3):.2f} GB")
    print(f"Available memory: {memory.available / (1024 ** 3):.2f} GB")
    print(f"CPU usage: {psutil.cpu_percent():.2f}%")
    elapsed = time.time() - start
    print(f"Elapsed time: {elapsed:.2f} seconds\n")

In [286]:
torch.manual_seed(42)
A = torch.randn(2 ** 10, 2 ** 16, dtype=torch.float64)
B = torch.randn(2 ** 16, 2 ** 5, dtype=torch.float64)
C = torch.randn(2 ** 5, 2 ** 14, dtype=torch.float64)

memory(torch.mm(A, B), C)
memory(A, torch.mm(B, C))

Total system memory: 63.22 GB
Memory used: 19.26 GB
Available memory: 43.96 GB
CPU usage: 13.30%
Elapsed time: 0.03 seconds

Total system memory: 63.22 GB
Memory used: 26.90 GB
Available memory: 36.32 GB
CPU usage: 70.70%
Elapsed time: 6.11 seconds



11. Consider three large matrices, say $\mathbf{A}\in \mathbb{R}^{2^{10}\times2^{16}}$, $\mathbf{B}\in \mathbb{R}^{2^{16}\times2^{5}}$ and $\mathbf{C}\in \mathbb{R}^{2^{5}\times2^{16}}$. Is there any difference in speed depending on whether you compute $\mathbf{AB}$ or $\mathbf{AC}$<sup>T</sup>? Why? What changes if you initialize  $\mathbf{C=B}$<sup>T</sup> without cloning memory? Why?

In [287]:
torch.manual_seed(42)
C = torch.randn(2 ** 5, 2 ** 16, dtype=torch.float64)

memory(A, B)
memory(A, C.T)

C = C.T
memory(A, C)

Total system memory: 63.22 GB
Memory used: 18.78 GB
Available memory: 44.44 GB
CPU usage: 40.30%
Elapsed time: 0.05 seconds

Total system memory: 63.22 GB
Memory used: 18.78 GB
Available memory: 44.44 GB
CPU usage: 68.80%
Elapsed time: 0.04 seconds

Total system memory: 63.22 GB
Memory used: 18.78 GB
Available memory: 44.44 GB
CPU usage: 68.80%
Elapsed time: 0.04 seconds





- Theoretically, the operations torch.mm(A, B) and torch.mm(A, C.T) should have similar performance in terms of computational complexity, but differ in memory access due to the data orientation of C.T. It was expected that transposition would negatively affect efficiency due to non-sequential memory access. However, the time difference between torch.mm(A, B) and torch.mm(A, C.T) is minimal. Perhaps the internal optimization of PyTorch for transpose operations is quite effective, minimizing the theoretically negative impact of memory transposition.

- Pre-transposing C and performing the multiplication with A shows a runtime comparable to torch.mm(A, B), with slightly reduced CPU usage. The reduction in CPU usage may be due to the elimination of the need for dynamic transposition during multiplication, indicating that pre-processing C might be beneficial from the perspective of reducing CPU load, despite not significantly impacting runtime.


12. Consider three matrices, say $\mathbf{A, B, C}\in \mathbb{R}^{100\times200}$. Construct a tensor with three axes by stacking $\mathbf{[A, B, C]}$. What is the dimensionality? Slice out the second coordinate of the third axis to recover $\mathbf{B}$. Check that your answer is correct.

In [288]:
torch.manual_seed(42)
A = torch.randn(100, 200, dtype=torch.float64)
B = torch.randn(100, 200, dtype=torch.float64)
C = torch.randn(100, 200, dtype=torch.float64)
torch.stack([A,B,C]).shape, torch.stack([A,B,C])[1] == B

(torch.Size([3, 100, 200]),
 tensor([[True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         ...,
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True]]))